server:
  port: 9001

spring:
  application:
    name: xdclass-user-service
  redis:
    host: 8.140.157.221
    password: 123456
    port: 8000
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: zzohn@foxmail.com #发送邮件的邮箱地址
    # 有时候授权码会失效 去qq邮箱里面重新配置就好啦
    password: bxfxyreussgoiibb #客户端授权码，不是邮箱密码,网易的是自己设置的
    from: zzohn@foxmail.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    # 防止不同云服务厂商之间的ip封禁
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8


  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.140.157.221:3306/xdclass_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

#配置plus打印sql日志 拼接好的那种便于使用sql语句定位问题
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO

# 阿里云
aliyun:
  #OSS配置
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9mDSiNK4jru72E7MWW
    access-key-secret: V0xy8Xg9UK6eNk8gF0lfjBFvh1nugV
    bucketname: xdclass-zohn-1024shop-image